services:
  cypress:
    build: .
    env_file:
      - .env
    environment:
      - CYPRESS_BASE_URL=${CYPRESS_BASE_URL:-http://localhost:4173}
    volumes:
      - ./cypress/videos:/app/cypress/videos
      - ./cypress/screenshots:/app/cypress/screenshots
